fix: modified the frontend
ArkaprabhaChakraborty/library-management-system pull request #13
Opened 2022-11-19 15:59 UTC by DebarghyaPal

Customised the Home Page, Login Portal and Signup Page

2022-11-19 16:05 UTC, DebarghyaPal commented
![image](https://user-images.githubusercontent.com/78264563/202860179-2bc28057-2e0e-488f-84c4-99c2f73a009c.png)

2022-11-19 16:06 UTC, DebarghyaPal commented
![image](https://user-images.githubusercontent.com/78264563/202860228-615cd05a-76d2-4211-b5f5-7c83e16f1bd4.png)

2022-11-19 16:06 UTC, DebarghyaPal commented
![image](https://user-images.githubusercontent.com/78264563/202860258-65cdc3dd-298e-49f2-8f45-eb1541b68e83.png)

2022-11-19 16:07 UTC, DebarghyaPal commented
![image](https://user-images.githubusercontent.com/78264563/202860291-978242cd-4294-4fd4-93f3-6d3779083058.png)

2022-11-19 16:15 UTC, ArkaprabhaChakraborty commented
Create a student account and an admin account and provide an ss for those too. After the creation of the account issue a book and provide those SS too. I need ss to be certain that everything works fine.

2022-11-19 16:18 UTC, ArkaprabhaChakraborty requested changes
Some necessary proofs are required so I can merge them into the main branch :). There can be multiple breaking changes so SS proofs are essential that we don't break essential functionalities.

2022-11-19 16:18 UTC, ArkaprabhaChakraborty commented on templates/student/login.html
> +{% block heading %} {% endblock heading %}
Why was this removed?

2022-11-19 16:18 UTC, ArkaprabhaChakraborty commented on templates/student/login.html
> +  {% comment %} {% if request.GET.next %}
Why were these comment templates added? As far as I know, these are [Liquid](https://shopify.github.io/liquid/). Did you use it? If so how did you manage the requirements for it?

2022-11-19 16:18 UTC, ArkaprabhaChakraborty commented on templates/student/signup.html
> -<form class="w-2xl sm:w-1/2 max-w-xs flex flex-col mx-auto -mt-8 sm:-mt-12" action="/student/signup/" method="POST">
Screenshot required to assert the correct behaviour

2022-11-19 16:18 UTC, ArkaprabhaChakraborty commented on templates/student/signup.html
> +  {% comment %} <div class="w-1/2  max-w-xs flex flex-col sm:flex-row mt-4  sm:items-center"></div>
Again ... liquid blocks out here...

2022-11-19 16:18 UTC, ArkaprabhaChakraborty commented on templates/student/signup.html
> +</div> {% endcomment %}
Liquid statements ... need ss as a proof to be certain that everything works fine

2022-11-19 16:22 UTC, ArkaprabhaChakraborty commented
> ![image](https://user-images.githubusercontent.com/78264563/202860228-615cd05a-76d2-4211-b5f5-7c83e16f1bd4.png)

Does the issue now on trending books work as expected? Does it redirect to the sign-in page if the user isn't logged in? If not the functionality changes have to be made in views.

2022-11-19 16:27 UTC, DebarghyaPal commented
![image](https://user-images.githubusercontent.com/78264563/202861224-ddf44247-91f5-462d-b0b9-24590602fbfd.png)

2022-11-19 16:34 UTC, DebarghyaPal commented
While trying to issue a book, it says, "You are not a student."

2022-11-19 17:00 UTC, DebarghyaPal commented on templates/student/login.html
> +  {% comment %} {% if request.GET.next %}
> Why were these comment templates added? As far as I know, these are [Liquid](https://shopify.github.io/liquid/). Did you use it? If so how did you manage the requirements for it?

I commented out the code snippets which I did not require. You can remove those from the file.

2022-11-19 17:01 UTC, DebarghyaPal commented on templates/student/signup.html
> -{% block heading %} Signup {% endblock heading %}
> Again ... why was this removed?

It wasn't looking great.

2022-11-19 17:02 UTC, DebarghyaPal commented on templates/student/login.html
> -<form class="w-2xl sm:w-1/2 max-w-xs flex flex-col mx-auto " action="/student/login/" method="POST">
> Why was this removed? Does the functionality remian the same for the form? Have you verified? If so can you attach a screenshot showing that it works as expected?

Yes, no alteration was done with the functionality.

2022-11-19 17:03 UTC, DebarghyaPal commented on templates/student/login.html
> +{% block heading %} {% endblock heading %}
> Why was this removed?

Wasn't looking great.

2022-11-25 18:19 UTC, ArkaprabhaChakraborty commented
I guess the student must be cteated properly and the student signup criteria has to be given by the admin first. Since that feature exists and we have asserted the correct usage I think the PR is good to be merged once we have all SS ready.

2022-11-26 05:17 UTC, DebarghyaPal commented
![Screenshot (1106)](https://user-images.githubusercontent.com/78264563/204073424-916c6087-f150-4e06-b2b6-a22a43257abc.png)
![Screenshot (1107)](https://user-images.githubusercontent.com/78264563/204073425-cfaa8d21-0313-40de-b2a7-e844cc098e6f.png)
![Screenshot (1108)](https://user-images.githubusercontent.com/78264563/204073426-10083ed1-03ae-4d38-9bca-93bcd30caefd.png)
![Screenshot (1109)](https://user-images.githubusercontent.com/78264563/204073427-f021fb8b-80aa-4789-b290-83fca3538000.png)
![Screenshot (1110)](https://user-images.githubusercontent.com/78264563/204073428-e1d8cd4a-f660-46c4-8641-cce43c44e154.png)
![Screenshot (1111)](https://user-images.githubusercontent.com/78264563/204073432-1489ce89-9438-476a-9a44-7932d2ffde1a.png)
![Screenshot (1112)](https://user-images.githubusercontent.com/78264563/204073433-bcd3ff7e-6428-4ecf-9771-4e0a5da6f05d.png)
![Screenshot (1113)](https://user-images.githubusercontent.com/78264563/204073435-c1684196-d8cb-4fa6-9908-8f5f3f82e328.png)
![Screenshot (1114)](https://user-images.githubusercontent.com/78264563/204073436-ca9c6cbe-4d53-4c50-b8eb-ad8541edcaeb.png)
![Screenshot (1115)](https://user-images.githubusercontent.com/78264563/204073437-34951003-58de-4dd1-895b-7d2cb2ed11d0.png)
![Screenshot (1116)](https://user-images.githubusercontent.com/78264563/204073438-53db7a31-92cd-444b-8af6-44a5c82dc4f1.png)
![Screenshot (1117)](https://user-images.githubusercontent.com/78264563/204073439-bdf02981-31d9-4d99-b310-fd2ecc64a578.png)
![Screenshot (1118)](https://user-images.githubusercontent.com/78264563/204073440-fa865041-b476-48c2-a100-439399ba4cba.png)
![Screenshot (1119)](https://user-images.githubusercontent.com/78264563/204073442-a787f737-59dc-476f-848a-45a52b8ed367.png)
![Screenshot (1120)](https://user-images.githubusercontent.com/78264563/204073443-c25b0e77-0d41-4ac7-a128-a962ae675eaf.png)
![Screenshot (1121)](https://user-images.githubusercontent.com/78264563/204073444-3847b69f-38ba-4b43-962e-ec5503a5c8d7.png)
![Screenshot (1122)](https://user-images.githubusercontent.com/78264563/204073445-40ec6eb3-20f0-4450-aafe-00d7c05d6d52.png)
![Screenshot (1123)](https://user-images.githubusercontent.com/78264563/204073446-c1993b0e-fca5-4119-bfcc-0bf587b1699f.png)
![Screenshot (1124)](https://user-images.githubusercontent.com/78264563/204073447-1a8e9139-4782-48b5-b7e9-b738441c15c1.png)
![Screenshot (1125)](https://user-images.githubusercontent.com/78264563/204073451-d67fa8e2-9154-47e0-9ccd-fd33e2084c92.png)
![Screenshot (1126)](https://user-images.githubusercontent.com/78264563/204073452-4f459c06-29c4-4da2-9a39-885deb6e19a5.png)
![Screenshot (1127)](https://user-images.githubusercontent.com/78264563/204073453-3b9cac12-5192-4139-b6a2-3fdbf5385cfb.png)
![Screenshot (1128)](https://user-images.githubusercontent.com/78264563/204073455-aa1b496e-3b32-4f39-9840-b59e0306b408.png)
![Screenshot (1129)](https://user-images.githubusercontent.com/78264563/204073456-1e16c304-aa68-4963-9715-d1d1b3a384a0.png)

2022-11-26 07:20 UTC, merged